@startuml

package building {
    class CircuitBuilder {

    }

    class CircuitBuilderDirector {

    }

    class CircuitDefinition {

    }

    class NodeFactory {

    }

    class NodeParentableVisitor {

    }

    enum NodeType {

    }
}

@enduml