@startuml

package validation {
    class CircuitInfiniteLoopValidator {
        +circuitHasInfiniteLoops(circuit: Circuit): boolean
        -detect(probe: Probe): boolean
        -detect(node: NodeComposite, visitedNodes: Set<Node>): boolean
    }

    class CircuitNotConnectedValidator {
        +hasDisconnectedProbes(circuit: Circuit): boolean
        -checkParenting(circuit: Circuit): boolean
    }
    CircuitNotConnectedValidator --> "1" NodeParentableVisitor : -visitor
}

@enduml