@startuml

package text {
    class TableNodeData {
        -name: String
        -type: String
        -output: boolean
        -parents: List<Node>

        +TableNodeData(type: String, name: String, output: boolean, parents: List<Node>)
        +getName(): String
        +getType(): String
        +getOutput(): String
        +getParents(): String
    }

    class TableNodeDrawingVisitor implements INodeVisitor {
        -value: TableNodeData

        +getValue(): TableNodeData
        +visit(node: Probe)
        +visit(node: Input)
        +visit(node: AndGate)
        +visit(node: NAndGate)
        +visit(node: NOrGate)
        +visit(node: OrGate)
        +visit(node: XOrGate)
    }
    TableNodeDrawingVisitor -> "1" TableNodeData: -value

    class TextSimulationView extends AbstractSimulationView {
        +TextSimulationView(controller: Controller, viewModel: ViewModel)
        #setupUi()
        #draw(circuit: Circuit)
    }
    TextSimulationView --> "1" TableNodeDrawingVisitor : -visitor
}

@enduml