@startuml
' Nodes
abstract class Node {
    +value: Observable<boolean>
    #previous: Set<Node>

    +{abstract} calculate()
}

class InputNode {
}
Node <|-- InputNode

class ProbeNode {
}
Node <|-- ProbeNode

' Ports
abstract class Port {
}
Node <|-- Port

class AndPort {
}
Port <|-- AndPort

class NAndPort {
}
AndPort <|-- NAndPort

class OrPort {
}
Port <|-- OrPort

class NorPort {
}
OrPort <|-- NorPort

class NotPort {
}
Port <|-- NotPort

class XorPort {
}
Port <|-- XorPort

' Circuit
class Circuit {
    -inputs: List<InputNode>
    -probes: List<ProbeNode>
}
InputNode <|.. Circuit
ProbeNode <|.. Circuit
Node <|-- Circuit
@enduml
