@startuml
autonumber

CircuitBuilder -> Circuit ** : new
CircuitBuilder -> Circuit ++ : simulate()

group foreach inputs
    Circuit -> InputNode ++ : calculate()

    InputNode -> InputNode : notify()
    InputNode -> Node ++ : calculate() "next"

    loop until the probes are reached
    Node -> Node : notify()
    Node -> Node ++ : calculate() "next"

    Node -> ProbeNode ++ : calculate()
    ProbeNode -> ProbeNode : notify()

    ProbeNode -> ProbeObserver ++ : probeChanged()
    ProbeNode --
    ProbeObserver --
    Node --

    end
    Node --
    InputNode --
end

Circuit --
@enduml