@startuml
autonumber

CircuitBuilder -> Circuit ** : new
CircuitBuilder -> Circuit ++ : simulate()

loop foreach inputs
    Circuit -> InputNode ++ : initialize()
    Circuit -> InputNode : calculate()
    InputNode --
end

Circuit --
@enduml